version: '3'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile.vite
    ports:
      - "3000:3000"

  graphql-server:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    ports:
      - "3001:3001"